version: "3"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=hibonly
      - MYSQL_PASSWORD=hibonly
      - MYSQL_ROOT_PASSWORD=rooty
    ports:
      - '3306:3306'